Inject.rawHead('loader-style', '<meta name="viewport" content="width=device-width,maximum-scale=1,'
+ 'initial-scale=1,user-scalable=no">'
+ '<style>'
+ 'html{background-color: #36342e;}'
+ 'body{color:#ddd;overflow:hidden !important;width:100%;}'
+ '.rotate {'
+ 'bottom:0;height:80px; width:80px;left:0;margin:auto;position:absolute;'
+ 'top:0;right:0;width:80px;'
+ '-webkit-animation: rotation .6s infinite linear;'
+ 'animation: rotation .6s infinite linear;'
+ 'border-left:6px solid rgba(194,194,194,.20);'
+ 'border-right:6px solid rgba(194,194,194,.20);'
+ 'border-bottom:6px solid rgba(194,194,194,.20);'
+ 'border-top:6px solid rgba(194,194,194,.9);'
+ 'border-radius:100%;'
+ 'z-index: 1200;'
+ '}'
+ '.spinner {'
+ 'z-index: 1100;'
+ 'position:fixed;'
+ 'top:0px;'
+ 'bottom:0px;'
+ 'left:0px;'
+ 'right:0px;'
+ 'background-color:white;'
+ '}'
+ '@-webkit-keyframes rotation {'
+ 'from {-webkit-transform: rotate(0deg);}'
+ 'to {-webkit-transform: rotate(359deg);}'
+ '}'
+ '@-moz-keyframes rotation {'
+ 'from {-moz-transform: rotate(0deg);}'
+ 'to {-moz-transform: rotate(359deg);}'
+ '}'
+ '@-o-keyframes rotation {'
+ 'from {-o-transform: rotate(0deg);}'
+ 'to {-o-transform: rotate(359deg);}'
+ '}'
+ '@keyframes rotation {'
+ 'from {transform: rotate(0deg);}'
+ 'to {transform: rotate(359deg);}'
+ '}'
+ '</style>');
Inject.rawHead('loader-body2', '<head><link rel="manifest" href="/gongmanifest.json"></head><body><div class="spinner"><div class="rotate"></div></div></body>');
